name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      CACHIX_NAME: nix-ci
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: '${{ env.CACHIX_NAME }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    #- run: nix flake check
    - run: nix-build -A checks.$(if [[ `uname` = Linux ]]; then echo x86_64-linux; else echo x86_64-darwin; fi)
  installer:
    if: github.event_name == 'push'
    needs: tests
    runs-on: ubuntu-latest
    env:
      CACHIX_NAME: nix-ci
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: '${{ env.CACHIX_NAME }}'
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: scripts/prepare-installer-for-github-actions
    - run: tar czf installer.tar.gz installer.sh # workaround for https://github.com/actions/upload-artifact/issues/38
    - uses: actions/upload-artifact@v2
      with:
        name: installer
        path: installer.tar.gz